- name: Install Jenkins
  hosts: all
  gather_facts: no

  tasks:
  - name: Install Java 8
    yum:
      name: java-1.8.0-openjdk
      state: latest
  - name: Enable Jenkins Stable Yum Repo
    yum_repository:
      name: jenkins-stable
      state: present
      description: Jenkins Stable Yum Repo
      baseurl: http://pkg.jenkins.io/redhat-stable
      gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
      gpgcheck: yes
  - name: Install Jenkins
    yum:
      name: jenkins
      state: latest
  - name: Enable Jenkins Service
    service:
      name: jenkins
      enabled: yes
  - name: Install Util RPM Packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - ansible
      - git
      - unzip
      - zip
  - name: Enable Software Collections Yum Repo
    yum:
      name: centos-release-scl
      state: latest
  - name: Install SCL Ruby 2.4
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - rh-ruby24
      - rh-ruby24-rubygem-bundler
      - rh-ruby24-ruby-devel
      - gcc
